function C = C_sys(Ix,Iy,Iz,b,b_dot,k,k_dot,l,m,t,t_dot)
%C_SYS
%    C = C_SYS(IX,IY,IZ,B,B_DOT,K,K_DOT,L,M,T,T_DOT)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    07-Sep-2021 10:57:24

