function G = G_function(E_1,E_2,Iy_1,Iy_2,g,l_1,l_2,m_1,theta_1,theta_2)
%G_FUNCTION
%    G = G_FUNCTION(E_1,E_2,IY_1,IY_2,G,L_1,L_2,M_1,THETA_1,THETA_2)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    12-Aug-2021 14:59:21

if ((1.0./1.0e+2 < abs(theta_1)) & (1.0./1.0e+2 < abs(theta_2)))
    t0 = -m_1.*conj(g).*((l_1.*cos(theta_1))./theta_1-l_1.*1.0./theta_1.^2.*sin(theta_1)-(l_2.*sin(theta_1).*sin(theta_2))./theta_2+(l_2.*cos(theta_1).*(cos(theta_2)-1.0))./theta_2)+E_1.*Iy_1.*theta_1-(l_1.*m_1.*conj(g).*cos(theta_1))./theta_1+l_1.*m_1.*1.0./theta_1.^2.*conj(g).*sin(theta_1);
elseif ((1.0./1.0e+2 < abs(theta_1)) & (abs(theta_2) < 1.0./1.0e+2))
    t0 = -m_1.*conj(g).*((l_2.*theta_2.*cos(theta_1))./2.0-l_2.*sin(theta_1).*(theta_2.^2./6.0+1.0)+(l_1.*cos(theta_1))./theta_1-l_1.*1.0./theta_1.^2.*sin(theta_1))+E_1.*Iy_1.*theta_1-(l_1.*m_1.*conj(g).*cos(theta_1))./theta_1+l_1.*m_1.*1.0./theta_1.^2.*conj(g).*sin(theta_1);
elseif ((abs(theta_1) < 1.0./1.0e+2) & (1.0./1.0e+2 < abs(theta_2)))
    t0 = -m_1.*conj(g).*((l_1.*theta_1)./3.0-(l_2.*sin(theta_1).*sin(theta_2))./theta_2+(l_2.*cos(theta_1).*(cos(theta_2)-1.0))./theta_2)+E_1.*Iy_1.*theta_1-(l_1.*m_1.*theta_1.*conj(g))./3.0;
elseif ((abs(theta_1) < 1.0./1.0e+2) & (abs(theta_2) < 1.0./1.0e+2))
    t0 = E_1.*Iy_1.*theta_1-m_1.*conj(g).*((l_1.*theta_1)./3.0+(l_2.*theta_2.*cos(theta_1))./2.0-l_2.*sin(theta_1).*(theta_2.^2./6.0+1.0))-(l_1.*m_1.*theta_1.*conj(g))./3.0;
else
    t0 = NaN;
end
if ((1.0./1.0e+2 < abs(theta_1)) & (1.0./1.0e+2 < abs(theta_2)))
    t1 = E_2.*Iy_2.*theta_2+m_1.*conj(g).*(-(l_2.*cos(theta_1).*cos(theta_2))./theta_2+l_2.*1.0./theta_2.^2.*cos(theta_1).*sin(theta_2)+(l_2.*sin(theta_1).*sin(theta_2))./theta_2+l_2.*1.0./theta_2.^2.*sin(theta_1).*(cos(theta_2)-1.0));
elseif ((1.0./1.0e+2 < abs(theta_1)) & (abs(theta_2) < 1.0./1.0e+2))
    t1 = E_2.*Iy_2.*theta_2-m_1.*conj(g).*((l_2.*sin(theta_1))./2.0+(l_2.*theta_2.*cos(theta_1))./3.0);
elseif ((abs(theta_1) < 1.0./1.0e+2) & (1.0./1.0e+2 < abs(theta_2)))
    t1 = E_2.*Iy_2.*theta_2+m_1.*conj(g).*(-(l_2.*cos(theta_1).*cos(theta_2))./theta_2+l_2.*1.0./theta_2.^2.*cos(theta_1).*sin(theta_2)+(l_2.*sin(theta_1).*sin(theta_2))./theta_2+l_2.*1.0./theta_2.^2.*sin(theta_1).*(cos(theta_2)-1.0));
elseif ((abs(theta_1) < 1.0./1.0e+2) & (abs(theta_2) < 1.0./1.0e+2))
    t1 = E_2.*Iy_2.*theta_2-m_1.*conj(g).*((l_2.*sin(theta_1))./2.0+(l_2.*theta_2.*cos(theta_1))./3.0);
else
    t1 = NaN;
end
G = [t0;t1];
